### ISSUE TITLE
Plugin Tools

### ISSUE THREAD

**Issue by marky-mark** [odavid/my-bloody-jenkins#126]
We have a few plugins for the tools section e.g. custom-tools-plugin, nodejs, sbt, xcode. These are added to the tools section in the UI once installed. All these look outside the support, is there a generic way of using installing these tools?

**Comment by odavid** [comment]
Hi,
I've added the following plugins to the image itself. As for configuration, here is an example of custom-tool and sbt using [configuration_as_code section](https://github.com/odavid/my-bloody-jenkins/blob/master/README.md#configuration-as-code-section). Any other plugins can be configured in the same manner.

```yaml
configuration_as_code:
  tool:
    customTool:
      installations:
      - name: "tool-name"
        home: /x/y/z
        properties:
        - installSource:
            installers:
            - command:
                command: >
                  curl -o tool-name.tar. -L | ...
    sbtInstallation:
      installations:
      - name: my-sbt
        sbtArguments: -Dxyz=zzz
        home: "" ## Jenkins will take care, since it is auto installer
        properties:
        - installSource:
            installers:
            - sbtInstaller:
                id: '1.2.8'
```
