### ISSUE TITLE
support bitbucket server configuration

### ISSUE THREAD

**Issue by danielezer** [odavid/my-bloody-jenkins#131]
Support configuring bitbucket server. This will enable using a bitbucket organisation folder

**Comment by odavid** [comment]
Hi @danielezer, you can use Configuration As Code section for doing so: 

```yaml
configuration_as_code:
  unclassified:
    bitbucketEndpointConfiguration:
      endpoints:
        - bitbucketCloudEndpoint:
            enableCache: true
            teamCacheDuration: 10
            repositoriesCacheDuration: 10
            manageHooks: true
            credentialsId: xys
        - bitbucketServerEndpoint:
            displayName: myname
            serverUrl: https://xty
            manageHooks: true
            credentialsId: xyz
            webhookImplementation: PLUGIN
```
