### ISSUE TITLE
Support for JCasC Groovy plugin

### ISSUE THREAD

**Issue by kmcquade** [odavid/my-bloody-jenkins#136]
Support for https://github.com/jenkinsci/configuration-as-code-groovy-plugin would be excellent.

**Comment by odavid** [comment]
Hi @kmcquade, if you add the plugin to the image (see my [comment about ec2 plugin](https://github.com/odavid/my-bloody-jenkins/issues/137#issuecomment-471159195) )
Then configuration_as_code section will support it 

```yaml
configuration_as_code:
  groovy:
    - script: >
        println("This is Groovy script!");
```
