### ISSUE TITLE
Support for EC2, not just ECS

### ISSUE THREAD

**Issue by kmcquade** [odavid/my-bloody-jenkins#137]
Looks like ECS is only supported at this time. @odavid this would be super useful to us...

**Comment by odavid** [comment]
I tried to focus only on docker based clouds, and since you can mix `configuration as code` yaml with the groovy based yaml, it is actually supported.

You will need to install [ec2 plugin](https://plugins.jenkins.io/ec2) within your image. 

* Use environment variable - `JENKINS_ENV_PLUGINS=ec2`
* Or bake it within your own image using `FROM odavid/my-bloody-jenkins:lts`

Then, you can use `configuration_as_code` section to add an ec2 cloud configuration.
 
```yaml
# String cloudName, boolean useInstanceProfileForCredentials, String credentialsId, String region, String privateKey, String instanceCapStr, List<? extends SlaveTemplate> templates, String roleArn, String roleSessionName
configuration_as_code:
  jenkins:
    clouds:
     - amazonEC2:
        cloudName: "docker-agents"
        useInstanceProfileForCredentials: false
        credentialsId: "jenkins-aws"
        region: "eu-central-1"

        privateKey: |-
          -----BEGIN RSA PRIVATE KEY-----
          MI+hN2ttKekpO3w.....
          ....
          -----END RSA PRIVATE KEY-----
        templates:
        - ami: "ami-xyz"
          amiType:
            unixData:
              sshPort: "22"
          associatePublicIp: false
          connectBySSHProcess: false
          connectUsingPublicIp: false
          deleteRootOnTermination: false
          description: "docker"
          ebsOptimized: false
          idleTerminationMinutes: "10"
          labelString: "docker ubuntu linux"
          mode: NORMAL
          monitoring: false
          numExecutors: 1
          remoteAdmin: "ubuntu"
          securityGroups: "docker"
          stopOnTerminate: false
          type: T2Micro
          useDedicatedTenancy: false
          useEphemeralDevices: false
          usePrivateDnsName: false
```
