### ISSUE TITLE
Seed job branch as variable 

### ISSUE THREAD

**Issue by jkornata** [odavid/my-bloody-jenkins#176]
I've successfully transitioned my Jenkins instance to My Bloody Jenkins version `2.235.5-215`

The only exception is that one of the seed jobs has variable as a source branch. Unfortunately it doesn't work and with each Jenkins boot it sets the value to `master` (I assume it's default value). 

```
managedConfig:
  seed_jobs:
    MyJobName:
      source:
        remote: link
        credentialsId: key
        branch: '${BRANCH_NAME}'
```

After each start I manually set it to desired value but each restart resets it. 

Variable is defined in my pipeline file:

```
pipeline {
    agent {
        label 'master'
    }
    parameters {
        string(name: 'BRANCH_NAME', defaultValue: '')

```

Is there any way to avoid setting this value to `master`?

**Comment by odavid** [comment]
Hi,
Escape it with backslash

**Comment by odavid** [comment]
@jkornata 

Like this:

```yaml
managedConfig:
  seed_jobs:
    MyJobName:
      source:
        remote: link
        credentialsId: key
        branch: '\${BRANCH_NAME}'
```
see https://github.com/odavid/my-bloody-jenkins#environment-variable-substitution-and-remove-master-env-vars
