### ISSUE TITLE
Docker Clouds Configuration

### ISSUE THREAD

**Issue by amihab** [odavid/my-bloody-jenkins#193]
Hi Ohad,

Long time, hope you are doing well ...

I am trying to configure the Clouds -> Docker -> Docker Agent templates -> Container settings --> Shared Memory Size in MB

Looks like setting is available in ecs clouds, but missing in docker cloud,.

Thanks in advance!!

**Comment by odavid** [comment]
Hi @amihab!
Hope you are doing well as well 😄 

Created a PR and will merge and release when it is ready.
Best!

**Comment by odavid** [comment]
@amihab 

```yaml
  docker-cloud:
    type: docker
    templates:
      - name: dockerslave
        image: jenkinsci/jnlp-slave:latest
        shmSize: 100 # size in MB
```
A release is on its way...
