### ISSUE TITLE
Add ability to define dynamic credential types

### ISSUE THREAD

**Issue by odavid** [odavid/my-bloody-jenkins#59]
Since not all credential types are supported as first citizen, let the user define the class name and the arguments of a credential that is not a first citizen.
The config handler should use java reflection to create the credential
```yaml
credentials:
  my-custom-cred:
   type: custom
   classname: com.whatever.cred.CredImpl
   args:
    - arg1
    - arg2
```
