### ISSUE TITLE
Support of fileOnMaster for credentials type sshkey

### ISSUE THREAD

**Issue by mrahbar** [odavid/my-bloody-jenkins#70]
First of all great Container Image, I like your groovy based approach!!

## Issue description
As a Kubernetes user I natively mount in ssh keys from secrets into the jenkins container. Thus I reference my ssh key as a file reference on the master. Currently the CredsConfig does not support this kind of settings e.g.

```
credentials:
  my-ssh-key:
    type: sshkey
    description: "SSH key"
    username: foo
    fileOnMaster: /.ssh/id_rsa <--- not supported yet
```

Here is a code snippet which I use for my custom build image. It would be great if you adapt this in your base image so I can drop my custom images.
```
def sshKeyCred(config) {
    def key
    if (config.fileOnMaster) {
        key = new BasicSSHUserPrivateKey.FileOnMasterPrivateKeySource(config.fileOnMaster)
    } else if (config.privatekey) {
        key = new BasicSSHUserPrivateKey.DirectEntryPrivateKeySource(new String(config.base64?.decodeBase64(), 'UTF-8'))
    }

    config.with{
        return new BasicSSHUserPrivateKey(CredentialsScope.GLOBAL,
            id,
            username,
            key,
            passphrase,
            description
        )
    }
}
```
